language: python
python:
- "3.12"

before_install:
- "export DISPLAY=:99.0"

install: 
- pip install .
- pip install worldbuild
- pip install coverage
- pip install nose coverage
- pip install coveralls
- pip install pathfinder
- pip install aikif

script:  
- nosetests --with-coverage

after_success:
  coveralls 
